// Minimal tui.toml rewriting for --install / --uninstall. This is NOT a
// general TOML parser: it only locates the [status_line] section and adds,
// replaces or removes its `command = "..."` line, preserving everything
// else (including `items`) byte-for-byte.

function tomlEscape(s) {
  return s
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\t/g, '\\t')
    .replace(/\r/g, '\\r')
    .replace(/\n/g, '\\n');
}

function findSection(lines, name) {
  const header = new RegExp(`^\\s*\\[${name.replace('.', '\\.')}\\]\\s*$`);
  for (let i = 0; i < lines.length; i++) {
    if (header.test(lines[i])) {
      let end = lines.length;
      for (let j = i + 1; j < lines.length; j++) {
        if (/^\s*\[/.test(lines[j])) { end = j; break; }
      }
      return { start: i, end };
    }
  }
  return null;
}

function isCommandLine(line) {
  return /^\s*command\s*=/.test(line);
}

/** Decode the TOML string forms accepted for a status-line command. */
function commandValueFromLine(line) {
  const rhs = line.match(/^\s*command\s*=\s*(.*)$/)?.[1];
  if (rhs === undefined) return { kind: 'absent', value: null };

  const basic = rhs.match(/^"((?:[^"\\]|\\.)*)"\s*(?:#.*)?$/);
  if (basic) {
    try {
      const value = JSON.parse(`"${basic[1]}"`);
      return typeof value === 'string'
        ? { kind: 'parsed', value }
        : { kind: 'unknown', value: null };
    } catch {
      return { kind: 'unknown', value: null };
    }
  }

  // TOML literal strings do not process escapes. A one-line command cannot
  // contain a literal single quote in this form.
  const literal = rhs.match(/^'([^']*)'\s*(?:#.*)?$/);
  if (literal) return { kind: 'parsed', value: literal[1] };
  return { kind: 'unknown', value: null };
}

/**
 * Inspect [status_line].command without conflating a missing key with a key
 * whose syntax we cannot safely interpret. Unknown syntax is intentionally
 * fail-closed so the SessionStart hook never overwrites user configuration.
 * @param {string} content
 * @returns {{kind: 'absent'|'parsed'|'unknown', value: string|null}}
 */
export function inspectStatusLineCommand(content) {
  const lines = (content || '').replace(/\r\n/g, '\n').split('\n');
  const section = findSection(lines, 'status_line');
  if (!section) return { kind: 'absent', value: null };
  for (let i = section.start + 1; i < section.end; i++) {
    if (isCommandLine(lines[i])) return commandValueFromLine(lines[i]);
  }
  return { kind: 'absent', value: null };
}

function safeCommandWords(command) {
  if (typeof command !== 'string') return null;
  const words = [];
  let word = '';
  let quote = null;
  let started = false;
  for (let i = 0; i < command.length; i++) {
    const char = command[i];
    if (quote) {
      if (char === quote) {
        quote = null;
      } else if (char === '\\' && quote === '"' && i + 1 < command.length) {
        word += command[++i];
      } else {
        word += char;
      }
      started = true;
      continue;
    }
    if (char === '"' || char === "'") {
      quote = char;
      started = true;
      continue;
    }
    if (/\s/.test(char)) {
      if (started) {
        words.push(word);
        word = '';
        started = false;
      }
      continue;
    }
    if (/[;&|<>()`]/.test(char)) return null;
    if (char === '$' && command[i + 1] === '(') return null;
    word += char;
    started = true;
  }
  if (quote) return null;
  if (started) words.push(word);
  return words;
}

/**
 * True only for the Node command generated by this HUD: `node` plus a path
 * ending in kimi-hud.mjs, optionally followed by simple flag arguments (older
 * installs may have added those by hand): `--flag`, `--flag=value`, or a
 * `--flag value` pair. Anything else — stray positional words, odd flag
 * shapes, shell metacharacters — stays foreign so unknown commands are never
 * rewritten.
 */
export function isKimiHudCommand(command) {
  const words = safeCommandWords(command);
  if (!words || words.length < 2) return false;
  const executable = words[0].replace(/\\/g, '/').split('/').at(-1)?.toLowerCase();
  const script = words[1].replace(/\\/g, '/').split('/').at(-1);
  if ((executable !== 'node' && executable !== 'node.exe') || script !== 'kimi-hud.mjs') {
    return false;
  }
  let expectsValue = false;
  for (const word of words.slice(2)) {
    if (/^--[A-Za-z][A-Za-z0-9-]*(=[A-Za-z0-9._/:-]+)?$/.test(word)) {
      expectsValue = !word.includes('=');
      continue;
    }
    if (expectsValue && /^[A-Za-z0-9._/:-]+$/.test(word)) {
      expectsValue = false;
      continue;
    }
    return false;
  }
  return true;
}

/**
 * Return tui.toml content with the status-line command installed.
 * Idempotent: running twice yields the same content. Preserves an existing
 * [status_line] section (e.g. its `items`) and appends a new section when
 * none exists.
 * @param {string} content existing file content (may be empty)
 * @param {string} command e.g. 'node /abs/path/bin/kimi-hud.mjs'
 * @returns {string}
 */
export function setStatusLineCommand(content, command) {
  const line = `command = "${tomlEscape(command)}"`;
  const lines = (content || '').replace(/\r\n/g, '\n').split('\n');
  // Trim trailing blank lines so appends stay tidy; restored at the end.
  while (lines.length > 0 && lines[lines.length - 1].trim() === '') lines.pop();

  const section = findSection(lines, 'status_line');
  if (!section) {
    if (lines.length > 0) lines.push('');
    lines.push('[status_line]', line);
    return lines.join('\n') + '\n';
  }
  for (let i = section.start + 1; i < section.end; i++) {
    if (isCommandLine(lines[i])) {
      if (lines[i] === line) return (content.endsWith('\n') ? content : content + '\n');
      lines[i] = line;
      return lines.join('\n') + '\n';
    }
  }
  lines.splice(section.start + 1, 0, line);
  return lines.join('\n') + '\n';
}

/**
 * Return the `command` value inside the [status_line] section, or null when
 * the section or its command line is absent. Other sections' `command` keys
 * (e.g. [editor]) are ignored.
 * @param {string} content
 * @returns {string | null}
 */
export function getStatusLineCommand(content) {
  const inspected = inspectStatusLineCommand(content);
  return inspected.kind === 'parsed' ? inspected.value : null;
}

/**
 * Return tui.toml content with the status-line command removed. Only
 * command lines inside [status_line] whose value mentions our script (or
 * equals the given command) are removed; other keys are untouched. When
 * nothing but blank lines remain in the section, the whole [status_line]
 * section (header included) is dropped instead of leaving an empty husk.
 * @param {string} content
 * @param {string} command
 * @returns {string}
 */
export function removeStatusLineCommand(content, command) {
  const lines = (content || '').replace(/\r\n/g, '\n').split('\n');
  const section = findSection(lines, 'status_line');
  if (!section) return content;
  const kept = [];
  for (let i = section.start + 1; i < section.end; i++) {
    const l = lines[i];
    const parsed = commandValueFromLine(l);
    if (
      isCommandLine(l) &&
      parsed.kind === 'parsed' &&
      (parsed.value === command || isKimiHudCommand(parsed.value))
    ) continue;
    kept.push(l);
  }
  if (kept.every((l) => l.trim() === '')) {
    const out = [...lines.slice(0, section.start), ...lines.slice(section.end)];
    while (out.length > 0 && out[out.length - 1].trim() === '') out.pop();
    return out.length === 0 ? '' : out.join('\n') + '\n';
  }
  return [...lines.slice(0, section.start + 1), ...kept, ...lines.slice(section.end)].join('\n');
}
